export const javascriptTopics = [
  "Variables and Data Types",
  "Operators",
  "Control Structures",
  "Loops",
  "Functions",
  "ES6 Syntax",
  "Arrow Functions",
  "Template Literals",
  "Destructuring",
  "Spread and Rest Operators",
  "Objects",
  "Arrays",
  "Array Methods",
  "String Methods",
  "Date and Time",
  "Math Object",
  "Type Coercion",
  "Error Handling",
  "Promises",
  "Async/Await",
  "Callback Functions",
  "Event Loop",
  "Closures",
  "Hoisting",
  "Scope and Scope Chain",
  "Lexical Scoping",
  "IIFE (Immediately Invoked Function Expressions)",
  "Modules and Imports/Exports",
  "Default Parameters",
  "Symbols",
  "Iterators and Generators",
  "Map and Set",
  "WeakMap and WeakSet",
  "Classes",
  "Inheritance",
  "Prototypes and Prototype Chain",
  "This Keyword",
  "Context Binding",
  "Higher Order Functions",
  "Functional Programming",
  "Pure Functions",
  "Currying",
  "Memoization",
  "Recursion",
  "Event Handling",
  "Event Bubbling and Capturing",
  "DOM Manipulation",
  "DOM Events",
  "Form Validation",
  "Local Storage",
  "Session Storage",
  "Cookies",
  "Fetch API",
  "AJAX",
  "JSON",
  "Regular Expressions",
  "Web APIs",
  "Web Workers",
  "Service Workers",
  "Push Notifications",
  "IndexedDB",
  "File API",
  "Canvas API",
  "Geolocation API",
  "History API",
  "Drag and Drop API",
  "Promises vs Callbacks",
  "Promise.all, Promise.race",
  "Generators and Async Iteration",
  "Proxy and Reflect",
  "BigInt",
  "Dynamic Imports",
  "Optional Chaining",
  "Nullish Coalescing",
  "Intl (Internationalization)",
  "Typed Arrays",
  "Decorators (proposal)",
  "Mixins",
  "Shadow DOM",
  "Custom Elements",
  "Template Element",
  "Mutation Observers",
  "Resize Observer",
  "Intersection Observer",
  "Pointer Events",
  "Touch Events",
  "Web Sockets",
  "WebRTC",
  "Performance Optimization",
  "Memory Management",
  "Garbage Collection",
  "Event Delegation",
  "Polyfills",
  "Babel",
  "Webpack",
  "Parcel",
  "TypeScript",
  "Flow",
  "Linting",
  "Unit Testing",
  "Integration Testing",
  "End-to-End Testing",
  "TDD (Test-Driven Development)",
  "BDD (Behavior-Driven Development)",
  "Debugging Techniques",
  "Code Style and Best Practices",
];


export const c_cppTopics = [
  "Variables and Data Types",
  "Operators",
  "Control Structures",
  "Loops",
  "Functions",
  "Pointers",
  "Arrays",
  "Strings",
  "Structures",
  "Unions",
  "Enumerations",
  "Bit Manipulation",
  "Preprocessor Directives",
  "Macros",
  "Conditional Compilation",
  "File I/O",
  "Dynamic Memory Allocation",
  "Memory Management",
  "Standard Library Functions",
  "Command-Line Arguments",
  "Inline Functions",
  "Namespaces",
  "Classes and Objects",
  "Inheritance",
  "Polymorphism",
  "Encapsulation",
  "Abstraction",
  "Constructors and Destructors",
  "Operator Overloading",
  "Function Overloading",
  "Templates",
  "STL (Standard Template Library)",
  "Vectors",
  "Lists",
  "Deques",
  "Stacks",
  "Queues",
  "Priority Queues",
  "Sets",
  "Maps",
  "Iterators",
  "Algorithms (STL)",
  "Exception Handling",
  "Type Casting",
  "Const Correctness",
  "Static Members",
  "Friend Functions",
  "Friend Classes",
  "Virtual Functions",
  "Pure Virtual Functions",
  "Abstract Classes",
  "Multiple Inheritance",
  "Virtual Inheritance",
  "RAII (Resource Acquisition Is Initialization)",
  "Smart Pointers",
  "Move Semantics",
  "Rvalue References",
  "Lambda Expressions",
  "Function Objects (Functors)",
  "Multithreading",
  "Mutexes and Locks",
  "Condition Variables",
  "Thread Local Storage",
  "Atomic Operations",
  "Memory Model",
  "Chrono Library",
  "Random Number Generation",
  "Regular Expressions",
  "Filesystem Library",
  "C++20 Concepts",
  "C++20 Ranges",
  "C++20 Coroutines",
  "Design Patterns",
  "SOLID Principles",
  "Memory Leaks",
  "Profiling and Optimization",
  "Debugging Techniques",
  "Makefile",
  "CMake",
  "Linking and Libraries",
  "Static Libraries",
  "Dynamic Libraries",
  "Compilation Process",
  "Inline Assembly",
  "Embedded Systems Programming",
  "Network Programming",
  "Socket Programming",
  "Inter-Process Communication",
  "Shared Memory",
  "Message Queues",
  "Semaphores",
  "Signals",
  "POSIX Threads",
  "Real-Time Programming",
  "Graphical User Interfaces (GUIs)",
  "Game Development",
  "Legacy Code Maintenance",
  "Best Practices",
  "Coding Standards",
  "Code Review",
  "Version Control Systems",
];


export const pythonTopics = [
    "Variables and Data Types",
    "Operators",
    "Control Structures",
    "Loops",
    "Functions",
    "Lambda Functions",
    "List Comprehensions",
    "Dictionaries",
    "Sets",
    "Tuples",
    "Strings",
    "String Formatting",
    "File I/O",
    "Exception Handling",
    "Modules and Packages",
    "Virtual Environments",
    "Standard Library",
    "Third-Party Libraries",
    "List Methods",
    "Dictionary Methods",
    "Set Methods",
    "Tuple Methods",
    "String Methods",
    "Decorators",
    "Generators",
    "Iterators",
    "Context Managers",
    "Closures",
    "Classes and Objects",
    "Inheritance",
    "Polymorphism",
    "Encapsulation",
    "Abstraction",
    "Static Methods",
    "Class Methods",
    "Instance Methods",
    "Magic Methods",
    "Properties",
    "Abstract Base Classes",
    "Meta Classes",
    "Multiple Inheritance",
    "Duck Typing",
    "Type Hinting",
    "Typing Module",
    "Functional Programming",
    "Higher Order Functions",
    "Map, Filter, Reduce",
    "Asyncio",
    "Coroutines",
    "Event Loop",
    "Concurrency",
    "Threading",
    "Multiprocessing",
    "Global Interpreter Lock (GIL)",
    "Regular Expressions",
    "File Handling",
    "CSV Handling",
    "JSON Handling",
    "XML Handling",
    "Logging",
    "Unit Testing",
    "Integration Testing",
    "Mocking",
    "Test-Driven Development (TDD)",
    "Behavior-Driven Development (BDD)",
    "Web Scraping",
    "Beautiful Soup",
    "Selenium",
    "Requests Library",
    "APIs",
    "RESTful Services",
    "GraphQL",
    "Django",
    "Flask",
    "FastAPI",
    "Database Connectivity",
    "SQLAlchemy",
    "Pandas",
    "Numpy",
    "Matplotlib",
    "Seaborn",
    "Data Visualization",
    "Data Analysis",
    "Machine Learning",
    "Scikit-Learn",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "Natural Language Processing",
    "OpenCV",
    "Image Processing",
    "Network Programming",
    "Socket Programming",
    "Async HTTP Clients",
    "Email Handling",
    "Python Packaging",
    "Pip",
    "Poetry",
    "Environment Variables",
    "Configuration Management",
    "Docker",
    "CI/CD Pipelines",
    "Profiling and Optimization",
    "Debugging Techniques",
    "Code Style and Best Practices",
    "PEP 8"
]


export const nodeExpressTopics = [
    "Node.js Basics",
    "Node.js Modules",
    "NPM (Node Package Manager)",
    "Package.json Configuration",
    "Node.js Core Modules",
    "File System Operations",
    "Streams and Buffers",
    "Event Emitters",
    "Child Processes",
    "Asynchronous Programming in Node.js",
    "Callbacks",
    "Promises",
    "Async/Await",
    "Error Handling in Node.js",
    "Debugging Node.js Applications",
    "Unit Testing with Jest or Mocha",
    "Integration Testing",
    "RESTful APIs",
    "HTTP Module",
    "Express.js Basics",
    "Routing in Express.js",
    "Middleware in Express.js",
    "Error Handling Middleware",
    "Template Engines (e.g., Pug, EJS)",
    "Static File Serving",
    "Form Handling",
    "Cookie Parsing",
    "Session Management",
    "Authentication Strategies",
    "Passport.js",
    "Authorization Middleware",
    "JWT (JSON Web Tokens)",
    "CORS (Cross-Origin Resource Sharing)",
    "File Uploads",
    "Database Connectivity",
    "MongoDB with Mongoose",
    "SQL Databases (e.g., MySQL, PostgreSQL) with Sequelize",
    "ORMs (Object-Relational Mappers)",
    "Database Migrations",
    "CRUD Operations",
    "Pagination",
    "Sorting",
    "Filtering",
    "Validation",
    "Error Handling",
    "RESTful API Design Best Practices",
    "Versioning APIs",
    "API Documentation",
    "API Security",
    "Rate Limiting",
    "Caching Strategies",
    "WebSockets",
    "Real-Time Communication",
    "Server-Sent Events (SSE)",
    "Testing APIs",
    "Mocking Dependencies",
    "Test Doubles (e.g., Spies, Stubs)",
    "Load Testing",
    "Security Best Practices",
    "HTTPS Configuration",
    "Input Sanitization",
    "Cross-Site Scripting (XSS) Prevention",
    "Cross-Site Request Forgery (CSRF) Protection",
    "Content Security Policy (CSP)",
    "Helmet.js",
    "Authentication Best Practices",
    "Password Hashing",
    "OAuth2",
    "Single Sign-On (SSO)",
    "Rate Limiting",
    "Logging",
    "Application Monitoring",
    "Error Monitoring",
    "Performance Monitoring",
    "Distributed Tracing",
    "Deployment Strategies",
    "Deploying Node.js Applications",
    "Containerization (Docker)",
    "Orchestration (Kubernetes)",
    "Serverless Architectures",
    "AWS Lambda",
    "Google Cloud Functions",
    "Microsoft Azure Functions",
    "CI/CD Pipelines",
    "Continuous Integration (CI)",
    "Continuous Deployment (CD)",
    "Monitoring and Alerting",
    "Scaling Strategies",
    "Microservices Architecture",
    "API Gateway",
    "Service Discovery",
    "Message Brokers (e.g., RabbitMQ, Kafka)",
    "Event-Driven Architecture",
    "GraphQL with Apollo Server",
    "Server-Side Rendering (SSR)",
    "Static Site Generation (SSG)",
    "Next.js Framework",
    "Nuxt.js Framework"
];


export const reactTopics = [
  "React Basics",
  "JSX (JavaScript XML)",
  "Components",
  "Functional Components",
  "Class Components",
  "Props",
  "State",
  "Lifecycle Methods",
  "Hooks",
  "useState Hook",
  "useEffect Hook",
  "useContext Hook",
  "useReducer Hook",
  "Custom Hooks",
  "Handling Events",
  "Conditional Rendering",
  "Lists and Keys",
  "Forms",
  "Controlled Components",
  "Uncontrolled Components",
  "Refs",
  "Forwarding Refs",
  "Context API",
  "Error Boundaries",
  "Fragments",
  "Portals",
  "Higher-Order Components (HOCs)",
  "Render Props",
  "Code Splitting",
  "Lazy Loading",
  "React Router",
  "React Router Dom",
  "Nested Routing",
  "Route Parameters",
  "Redirects",
  "Navigation Guards",
  "Server-Side Rendering (SSR)",
  "Static Site Generation (SSG)",
  "Next.js Framework",
  "Redux",
  "Redux Toolkit",
  "State Management",
  "Actions",
  "Reducers",
  "Selectors",
  "Immutability",
  "Middleware",
  "Thunk",
  "Saga",
  "Reselect",
  "Redux DevTools",
  "Redux Persist",
  "Redux Form",
  "Context API vs Redux",
  "GraphQL",
  "Apollo Client",
  "Querying Data",
  "Mutating Data",
  "Caching",
  "Authentication",
  "Authorization",
  "React Bootstrap",
  "Material-UI",
  "Styled Components",
  "CSS Modules",
  "CSS-in-JS",
  "Animation Libraries (e.g., Framer Motion)",
  "Testing with Jest and React Testing Library",
  "Unit Testing",
  "Integration Testing",
  "Component Testing",
  "Mocking Dependencies",
  "Snapshot Testing",
  "E2E Testing",
  "Cypress",
  "Enzyme",
  "Performance Optimization",
  "Memoization",
  "Virtual DOM",
  "Component Lifecycle Optimization",
  "Code Splitting",
  "Bundle Analysis",
  "Error Boundary Optimization",
  "Server-Side Rendering Optimization",
  "Progressive Web Apps (PWAs)",
  "Service Workers",
  "Web Accessibility (a11y)",
  "Keyboard Navigation",
  "Screen Readers",
  "Semantic HTML",
  "ARIA Attributes",
  "Web Performance Optimization",
  "Critical Rendering Path",
  "Image Optimization",
  "Lazy Loading Images",
  "Responsive Design",
  "Internationalization (i18n)",
  "Localization (l10n)",
  "SEO Best Practices",
  "Structured Data",
  "Canonical URLs",
  "Schema.org",
  "Social Metadata",
  "Open Graph Protocol",
  "Twitter Cards",
  "React Native",
  "Building Mobile Apps",
  "Deployment",
  "CI/CD Pipelines",
  "Continuous Integration (CI)",
  "Continuous Deployment (CD)",
];
